language: go

go:
        - master

install:
        - go get golang.org/x/tools/cmd/cover
        - go get github.com/mattn/goveralls
        - go get github.com/nsf/termbox-go

script:
        - go test -v -covermode=count -coverprofile=coverage.out
        - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken 4QQQxffQ92EBsN1Tob5MOAToyEy8FSGgx

os:
        - linux
        - osx
